"""Human-readable explanations of what each setup means when it's found --
shown in the app next to scan matches so a match isn't just a row of numbers.
"""

PATTERN_EXPLANATIONS = {
    "squeeze": (
        "Squeeze (primary system A). Fires on the QUIET/COILED day, BEFORE the breakout prints -- "
        "this is the direct answer to 'the breakout already happened': a momentum leader (RS "
        "rating), above a rising 50-day MA, sitting in a range that's meaningfully tighter than "
        "its own ADR over the last few days (self-normalized -- no hardcoded % threshold, since a "
        "3%-ADR stock and a 10%-ADR stock need very different absolute tightness to mean the same "
        "thing), that has NOT yet closed above its recent pivot high, following a genuine prior "
        "advance. A resting stop-buy above today's high catches the move live instead of chasing "
        "an already-confirmed one. Structurally complementary to Breakout: the same stock can "
        "never match both on the same day.\n\n"
        "⚠️ **Measured honestly, this is not yet a system worth trading as-is.** On the full "
        "2,418-symbol cached universe (2022-2026): 931 trades, 41.0% win rate, a barely-positive "
        "+0.12R per-trade expectancy (profit factor 1.03 -- essentially breakeven before costs), "
        "but the AGGREGATE portfolio result over the period was -30.7% CAGR against buy-and-hold "
        "SPY's own +25.0% CAGR over the same window -- a wide, real gap, not a rounding error. The "
        "root cause: a 'quiet, coiled' state is structurally far more common than a 'confirmed "
        "breakout' (931 signals here vs. Breakout's 449 over the same data), so this setup keeps "
        "many more correlated small-cap positions open at once than the shared backtest engine's "
        "default sizing (10 concurrent slots, 20% of equity each, 1% risked each) was tuned for -- "
        "a real concentration-risk problem, not a per-trade flaw. Likely worth retesting with "
        "fewer concurrent positions, smaller per-trade risk, or the regime/crowding filter "
        "(Backtest mechanics, Designer tab) turned on before trusting this with real capital. "
        "Kept as a primary system because the entry mechanic (catch the move before it breaks, "
        "not after) is the real fix for the 'already happened' complaint -- but the position "
        "sizing around it needs more work than this first pass gave it."
    ),
    "pullback": (
        "Pullback (primary system B). Buy the FIRST shallow pullback to a rising 10- or 20-day "
        "EMA in an already-confirmed RS leader, on light volume (a sellers-exhausted proxy), after "
        "having been meaningfully extended away from that same EMA recently -- proof this is a "
        "genuine pullback FROM an extended move, not chop that never left the average. Never "
        "requires a new high to trigger, so unlike a breakout entry it structurally can't feel "
        "'late' -- you're buying weakness within an already-established uptrend, not chasing "
        "strength.\n\n"
        "Measured on the full 2,418-symbol cached universe: 182 trades, 39.6% win rate, +0.13R "
        "expectancy, profit factor 1.28, -23.6% max drawdown, Sharpe 0.08 (weak but positive), "
        "CAGR +0.23% -- positive, but nowhere close to beating buy-and-hold SPY's +25.0% over the "
        "same window. On a smaller 400-symbol universe the picture flips negative entirely (31 "
        "trades, -0.16R) -- too small and too inconsistent a sample to call this validated either "
        "way. Better risk profile than Squeeze (real drawdown control, positive Sharpe), but "
        "'better than Squeeze' is a low bar here -- treat both as a starting point for further "
        "tuning, not a proven edge yet."
    ),
    "breakout": (
        "Qullamaggie Breakout. A stock already made a big move, then paused to consolidate for a "
        "few weeks in a tight range while 'surfing' its 10/20-day moving average -- a sign strong "
        "hands are holding, not dumping. A breakout to new highs on above-average volume means "
        "demand is stepping back in and the stock is resuming its prior trend. This is a "
        "momentum-continuation trade, not a reversal. Three optional, stricter checks are available "
        "but off by default (Designer tab): the 10/20-day EMAs actually sloping upward (not just "
        "sat above by price), genuinely higher lows in the base (not just a tight range), and the "
        "prior move being a real net advance rather than just a wide/choppy range -- each cuts "
        "match volume noticeably when turned on, so try them individually rather than all at once.\n\n"
        "Two more opt-in, off-by-default toggles target the fact that this exact setup is now "
        "common enough to be crowded: a recent-fakeout filter (penalize or exclude names that "
        "already faked out of this same level recently -- a mechanical proxy for real FX "
        "order-clustering evidence, Osler JFE 2003, not a claim about 'smart money'), and a "
        "close-confirmation requirement (only trigger if the breakout still holds a full day "
        "later). Confirmation adds a full extra day of delay, which cuts directly against getting "
        "in before the crowd.\n\n"
        "Measured on the full 2,418-symbol cached universe, all four combinations against the "
        "baseline (449 trades, 46.8% win, +0.15R, 1.31 PF): **excluding recent fakeouts** cuts match "
        "volume to almost nothing (13 trades) but with a higher win rate (61.5%) and expectancy "
        "(+0.18R) on that tiny sample -- too few trades to trust yet. **Requiring close confirmation** "
        "surprised the framing above: it actually *raised* trade count (488) while improving win "
        "rate (51.2%), expectancy (+0.20R) and profit factor (1.44) -- the extra day of lag did not "
        "cost what was assumed here, on this measurement. Combining both toggles lands in between "
        "(26 trades, +0.14R). None of this is enough to flip either default on, but confirmation in "
        "particular looks worth a longer look rather than dismissing on the a-priori 'adds lag' "
        "argument alone."
    ),
    "episodic_pivot": (
        "Episodic Pivot. A sudden, large gap up (often on an earnings surprise, guidance raise, "
        "or major news) on unusually heavy volume, in a stock that had been quiet or overlooked "
        "beforehand. Big growth numbers (EPS/revenue) are required whenever fundamentals data is "
        "available for the symbol, not just a scoring bonus, and a genuine earnings beat vs. "
        "analyst estimates adds further to the score when that data is available. The gap reflects "
        "a sharp, sudden re-rating of the business by the market -- these can be the start of a "
        "large new trend, but are also more news-driven and volatile than a technical breakout, so "
        "risk control matters even more here. Note: this scanner only ever sees end-of-day bars, so "
        "it can't verify the stricter 'gap confirmed in the first 5-30 minutes' intraday timing -- "
        "that confirmation is left to the trader."
    ),
    "parabolic_short": (
        "Parabolic Short (extension/reversal). A stock has run up so far, so fast, that it's "
        "trading many multiples of its normal daily range above its short-term moving average. "
        "This is a bet that the move has become unsustainable and is due for a sharp mean-reversion "
        "or blow-off-top reversal -- the counter-trend, short-side setup in the playbook. Higher "
        "risk than the long setups: you're betting against momentum, not with it."
    ),
    "cup_with_handle": (
        "Cup with Handle (O'Neil). The single most famous pattern in 'How to Make Money in Stocks'. "
        "After an uptrend, the stock corrects gradually and rounds out at the bottom like the base "
        "of a cup (not a sharp V), climbs back toward its old high, then forms a small 'handle' -- "
        "a shallow, low-volume pullback in the upper half of the cup that shakes out the last "
        "impatient holders. A breakout above the old high (and the handle) on a surge of volume "
        "signals that institutions are accumulating again and a new leg up is starting."
    ),
    "double_bottom": (
        "Double Bottom / 'W' (O'Neil). The stock makes a low, rallies, then comes back down to a "
        "similar (often slightly lower) low before rallying again -- tracing a 'W' shape. The "
        "second low undercutting the first is a classic shakeout of weak holders; the fact that "
        "sellers couldn't push price meaningfully lower the second time shows selling pressure is "
        "drying up. A breakout above the peak between the two lows, on volume, is the buy signal."
    ),
    "flat_base": (
        "Flat Base (O'Neil). A tight, boring, sideways consolidation -- no more than roughly "
        "10-15% from top to bottom -- lasting at least five weeks, usually after an existing "
        "uptrend or an earlier base. The tightness itself is the signal: nobody's in a hurry to "
        "sell, which means supply has dried up. A breakout above the top of the range on volume "
        "suggests the stock is ready to resume its advance."
    ),
    "ascending_base": (
        "Ascending Base (O'Neil). A choppier, staircase-shaped base: a series of pullbacks (often "
        "three), each with a higher low and a higher high than the last, each pullback shallower "
        "than a typical 20%+ correction. It looks messier than a cup or flat base, but the "
        "ascending structure shows buyers keep stepping in at higher prices -- persistent, "
        "building demand rather than a clean rest. Breakout above the most recent high on volume "
        "confirms it."
    ),
    "high_tight_flag": (
        "High Tight Flag (O'Neil). The rarest and most explosive pattern in the book: the stock "
        "rockets up 100%+ (sometimes 120%+) in just 4-8 weeks, then pauses in a remarkably tight "
        "flag for 3-5 weeks with a pullback of only ~10-25% -- astonishingly shallow given how far "
        "and fast it just ran. That tightness after such an extreme move suggests almost nobody is "
        "taking profits. When it works, it can mean a stock is just getting started on a much "
        "bigger move. It also has one of the highest failure rates of any pattern here precisely "
        "because the setup itself is so extreme -- size positions accordingly."
    ),
    "momentum_burst": (
        "Momentum Burst (Stockbee / Pradeep Bonde). The shortest-horizon setup here, and the one "
        "that best matches a 3-5 day hold. The idea: most short-term moves are 3-5 day 'bursts' of "
        "roughly 8-40%, and they start with a single range-expansion day out of a quiet, orderly "
        "consolidation. You take day one of the burst, hold a few days, sell into strength, and "
        "repeat -- the edge comes from doing it many times, not from catching one huge winner.\n\n"
        "The core scan is Bonde's own, unchanged since 2014: the stock closes up at least 4% on "
        "volume higher than the previous day. On top of that this adds his published quality "
        "checklist -- the breakout day must expand its range and close near its high; the day "
        "before should be a narrow or down day; the consolidation before it should be tight, quiet "
        "(volume drying up) and free of big swings; and the prior advance should be linear rather "
        "than choppy. It also skips a stock already up three days in a row, since by then the move "
        "is underway and your stop sits too far below to be worth taking.\n\n"
        "Why it's here: Qullamaggie credits Bonde as one of his own sources, and this is "
        "essentially the same idea on a much shorter timeframe. The trigger is simply the signal "
        "day's high, which suits a premarket stop-buy better than anything else in this app.\n\n"
        "⚠️ **It has not tested well here.** On 400 cached symbols over 2022-2026 with stop-buy "
        "entries it returned -0.23R expectancy at a 0.62 profit factor, against Breakout's +0.47R "
        "and 2.15. Its trailing exits average only +0.75R -- the winners never get large enough to "
        "pay for the losers -- and that held across faster trails and earlier partials, so it's the "
        "entries rather than the exit rules. Two likely reasons: this universe skews mid/large-cap "
        "while Bonde's method leans on smaller, more volatile names, and he treats the scan as a "
        "shortlist to judge by eye rather than as a mechanical system. Treat it as a scan worth "
        "tuning, not a system to trade as-is."
    ),
    "vcp": (
        "VCP / Volatility Contraction Pattern (Minervini). Inside a base, price pulls back several "
        "times, and each pullback is SHALLOWER than the one before it while volume also declines "
        "each time -- a fan of narrowing swings around one resistance level, not just 'the range is "
        "tight right now'. It ends in a final, tight, low-volume pivot before breaking out on volume. "
        "This app's Breakout setup only checks whether the base is tight at this moment; VCP instead "
        "detects the multi-leg contraction SEQUENCE itself, which most simple momentum-breakout bots "
        "don't implement -- the premise here is that this selects a smaller, less crowded subset of "
        "names than a plain tight-range scan. It's a heuristic swing-leg detector (rolling local "
        "highs/lows plus a bounded lookback over the last few legs), not pixel-perfect shape "
        "recognition, and real legs are rarely perfectly monotonic -- hence the tolerance settings. "
        "\n\n"
        "Measured on the full 2,418-symbol cached universe (a broader universe/period than the "
        "400-symbol comparison below, so not directly comparable line-for-line): only **5 trades**, "
        "60% win rate, +0.30R expectancy, 1.76 profit factor, -11.1% max drawdown. Genuinely rare by "
        "design -- this is exactly the 'smaller, less crowded subset' the pattern is meant to select "
        "-- but 5 trades is nowhere near enough to call this validated. Treat it as promising and "
        "worth widening the universe/period for, not as proven."
    ),
    "spring": (
        "Spring / Wyckoff Phase B-C shakeout. Inside a quiet trading range with volume already "
        "drying up, price briefly punches below range support -- undercutting the last obvious "
        "stop-loss cluster -- then reclaims the range within a few days, ideally WITHOUT a matching "
        "expansion in volume (a genuine breakdown would show more volume, not less). `match` fires "
        "on the reclaim day, while the stock is still sitting inside/near its range -- deliberately "
        "before any resistance-breakout bot would ever notice it, since nothing has broken out yet. "
        "This is a classical framework (Wyckoff, later formalized by Pruden), not a modern "
        "peer-reviewed finding, and it's described here purely mechanically: a structural "
        "false-breakdown-and-reclaim, no claim about 'smart money' intent. RS rating is deliberately "
        "not filtered by default, since a spring often precedes a stock becoming a leader rather "
        "than following one."
        "\n\n"
        "Measured on the full 2,418-symbol cached universe (a broader universe/period than the "
        "400-symbol comparison below): **229 trades**, 44.1% win rate, +0.12R expectancy, 1.31 profit "
        "factor, -41.7% max drawdown, Sharpe 0.23 -- a real sample size, positive expectancy, and a "
        "materially lower drawdown than Breakout measured the same way (-63.5%). Encouraging, not "
        "conclusive -- treat it the way this project treats every new setup until it's been "
        "cross-checked on a second universe/period."
    ),
}
